services:
    postgres:
        image: postgres:18
        container_name: stockvision-postgres
        restart: unless-stopped

        environment:
            POSTGRES_USER: stockvision
            POSTGRES_PASSWORD: stockvision
            POSTGRES_DB: stockvision

        ports:
            - "5432:5432"

        volumes:
            - postgres_data:/var/lib/postgresql

volumes:
    postgres_data:
